
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=${EXTERNAL_DB_HOST:-db}
      - DB_PORT=${EXTERNAL_DB_PORT:-3306}
      - DB_DATABASE=${EXTERNAL_DB_NAME:-laravel}
      - DB_USERNAME=${EXTERNAL_DB_USER:-root}
      - DB_PASSWORD=${EXTERNAL_DB_PASSWORD:-password}
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:6.2-alpine
    platform: linux/amd64
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - db
    networks:
      - laravel

volumes:
  db_data:
    driver: local

networks:
  laravel:
    driver: bridge